from django.urls import path

from app1 import views
 
 
urlpatterns = [
     
 
 
    path('',views.index),
    path('login/',views.login),
    path('logins/',views.logins),
    path('logout/',views.logout),
    path('admin_header/',views.admin_header),
    path('admin1/',views.admin1),
    path('police1/',views.police1),
    path('welfare1/',views.welfare1),
    path('counciler1/',views.counciler1),
    path('parent1/',views.parent1),
    path('student1/',views.student1),
    path('public_header/',views.public_header),
    path('student_header/',views.student_header),
    path('parent_header/',views.parent_header),
    path('counciler_header/',views.counciler_header),
    path('police_header/',views.police_header),
    path('police_viewcomplaint/',views.police_viewcomplaint),
    path('welfare_header/',views.welfare_header),
    path('welfare_viewcomplaint/',views.welfare_viewcomplaint),
    path('complaint/',views.complaint),
    path('take_action/<int:id>',views.take_action),
    path('actions/',views.actions),
    path('view_action/',views.view_action),
    path('view_action1/<str:id>/<str:id1>',views.view_action1),
    path('studentview_action/',views.studentview_action),
    path('studentview_action1/<str:id>/<str:id1>',views.studentview_action1),
    path('counciler_viewaction/',views.counciler_viewaction),
    path('counciler_viewaction1/<str:id>/<str:id1>',views.counciler_viewaction1),
    path('admin_viewaction/',views.admin_viewaction),
    path('admin_viewaction1/<str:id>/<str:id1>',views.admin_viewaction1),
    path('verify_action/',views.verify_action),
    path('verify_action1/<str:id>',views.verify_action1),
    path('viewdetails_welfare/<str:id>',views.viewdetails_welfare),
    path('viewdetails_police/<str:id>',views.viewdetails_police),
    path('police_takeaction/<str:id>',views.police_takeaction),
    path('police_action/',views.police_action),
    path('welfare_takeaction/<str:id>',views.welfare_takeaction),
    path('welfare_action/',views.welfare_action),
    path('verify_action2/',views.verify_action2),
    path('add_account1/',views.add_account1),
    path('add_notification/',views.add_notification),
    path('add_notification1/',views.add_notification1),
    path('add_awareness/',views.add_awareness),
    path('add_awareness1/',views.add_awareness1),
    
    path('remove_awareness/',views.remove_awareness),
    path('remove_awareness1/<int:id>',views.remove_awareness1),

    path('remove_notification/',views.remove_notification),
    path('remove_notification1/<int:id>',views.remove_notification1),

    path('add_account/',views.add_account),
    path('remove_account/',views.remove_account),
    path('parent_registration/<int:id>',views.parent_registration),
    path('parents/',views.parents),
    path('student_registration/',views.student_registration),
    path('complaint_registration/',views.complaint_registration),
    path('complaints/',views.complaints),
    path('complaint_registration1/',views.complaint_registration1),
    path('complaints1/',views.complaints1),
    path('students/',views.students),
    path('view_student/',views.view_student),
    path('view_notification/',views.view_notification),
    path('view_awareness/',views.view_awareness),
    path('remove_account1/<int:id>',views.remove_account1),
]
