# Generated by Django 4.1 on 2022-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_account',
            },
        ),
        migrations.CreateModel(
            name='tbl_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=30)),
                ('complaint_id', models.CharField(max_length=30)),
                ('views', models.CharField(max_length=30)),
                ('suggestions', models.CharField(max_length=40)),
                ('actiondetails', models.CharField(max_length=30)),
                ('redirectedTo', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_action',
            },
        ),
        migrations.CreateModel(
            name='tbl_awareness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness_id', models.CharField(max_length=30)),
                ('awareness_news', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_awareness',
            },
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30)),
                ('complaint', models.CharField(max_length=40)),
                ('complaint_dt', models.CharField(max_length=30)),
                ('accused', models.CharField(max_length=30)),
                ('accused_dt', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='tbl_complaint1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30)),
                ('complaint', models.CharField(max_length=40)),
                ('complaint_dt', models.CharField(max_length=30)),
                ('accused', models.CharField(max_length=30)),
                ('accused_dt', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_complaint1',
            },
        ),
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('complaint_id', models.IntegerField()),
                ('action_id', models.IntegerField()),
                ('policeaction_id', models.IntegerField()),
                ('welfareaction_id', models.IntegerField()),
                ('awareness_id', models.IntegerField()),
                ('notification_id', models.IntegerField()),
                ('complaints_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_idgen',
            },
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=30)),
                ('notification', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='tbl_parentreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=40)),
                ('parent_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_parentreg',
            },
        ),
        migrations.CreateModel(
            name='tbl_policeaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policeaction_id', models.CharField(max_length=30)),
                ('account_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('complaint_id', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_policeaction',
            },
        ),
        migrations.CreateModel(
            name='tbl_studentreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=40)),
                ('student_name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_studentreg',
            },
        ),
        migrations.CreateModel(
            name='tbl_welfareactn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welfareaction_id', models.CharField(max_length=30)),
                ('account_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('complaint_id', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_welfareactn',
            },
        ),
    ]
